spring.application.name=produto-api
server.port=8083

spring.data.mongodb.uri=mongodb://fatec:12345@54.242.251.117:27017/fatec
spring.data.mongodb.database=fatec

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration,org.springframework.boot.autoconfigure.security.oauth2.resource.servlet.OAuth2ResourceServerAutoConfiguration